version: "3.9"
services:
  database:
    image: 'postgres:14'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_database
  redis:
    image: 'redis:6.2'
    ports:
      - 6379:6379
